[package]
name = "portfolio"
version = "0.1.0"
edition = "2021"


[dependencies]
components = { version = "0.1.0", path="crates/components" }
yew = "0.19.3"


[workspace]
members = [ "crates/components" ]