[package]
authors = [ "c1m50c <https://github.com/c1m50c>" ]
name = "types"
version = "0.1.0"
edition = "2021"


[dependencies]
stylist = { version = "0.11.0", features = [ "yew" ] }
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.87"
once_cell = "1.16.0"