name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy-portfolio:
    concurrency: deploy-portfolio-peresonal-dot-com
    name: Deploy - `portfolio.peresonal.com`
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.13

      - name: Install Dependencies
        run: |
          bun install -g @azure/static-web-apps-cli
          bun install

      - name: Build - `portfolio.peresonal.com`
        run: |
          bun run build

      - name: Deploy - `portfolio.peresonal.com`
        run: |
          swa deploy --deployment-token ${{ secrets.APP_DEPLOYMENT_TOKEN }} --env Production
