name: Verify

on:
  pull_request:

jobs:
  verify-portfolio:
    name: Verify - `portfolio.peresonal.com`
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install Dependencies
        run: bun install

      - name: Verify - Check & Lint
        run: |
          bun run check
          bun run lint

      - name: Verify - Build
        run: |
          bun run build
